from pathlib import Path
path = Path('app/services/calculation_service.py')
text = path.read_text(encoding='utf-8')
old = "    def _normalize_subject_type(self, subject_config: Dict[str, Any]) -> str:\n        \"\"\"统一科目类型判断逻辑 - 与DataAdapterRepository保持一致\"\"\"\n        subject_type = subject_config.get('subject_type', '')\n        question_type_enum = subject_config.get('question_type_enum', '')\n        \n        if question_type_enum and question_type_enum.lower() == 'questionnaire':\n            return 'questionnaire'\n        elif subject_type:\n            return subject_type.lower()\n        else:\n            return 'exam'  # 默认考试类型\n"
new = "    def _normalize_subject_type(self, subject_config: Dict[str, Any]) -> str:\n        \"\"\"统一科目类型判断逻辑 - 与DataAdapterRepository保持一致\"\"\"\n        subject_name = subject_config.get('subject_name', '')\n        subject_type = subject_config.get('subject_type', '')\n        question_type_enum = subject_config.get('question_type_enum', '')\n        instrument_id = subject_config.get('instrument_id')\n\n        subject_type_value = (subject_type or '').strip().lower()\n        question_type_value = (question_type_enum or '').strip().lower()\n\n        if question_type_value == 'questionnaire' or subject_type_value == 'questionnaire':\n            return 'questionnaire'\n\n        if instrument_id:\n            instrument_value = str(instrument_id).strip().lower()\n            if any(token in instrument_value for token in ('likert', 'survey', 'questionnaire', '问卷')):\n                return 'questionnaire'\n\n        name_value = (subject_name or '').strip()\n        name_lower = name_value.lower()\n        for kw in self._questionnaire_keywords:\n            if kw and kw in name_value:\n                return 'questionnaire'\n        for kw in self._questionnaire_normalized:\n            if kw and kw in name_lower:\n                return 'questionnaire'\n\n        if subject_type_value:\n            return subject_type_value\n        if question_type_value:\n            return question_type_value\n        return 'exam'  # 默认考试类型\n"
if old not in text:
    raise SystemExit('original normalize_subject_type block not found')
text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')
